# Generated by Django 3.2.2 on 2022-05-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заглавие')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='заглавие')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='создать в')),
                ('Video', models.URLField(null=True, unique=True, verbose_name='видео')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.article', verbose_name='статья')),
            ],
        ),
    ]
